/**
 * aiReportWriter.js — Professional bug bounty report generator.
 *
 * Turns raw findings into submission-ready reports:
 *  - Executive summary
 *  - Per-finding: title, severity, CVSS-ish score, description,
 *    reproduction steps, PoC, impact, remediation
 *  - Written in clear, professional English (bounty-platform ready)
 */

import { generatePoC } from './pocGenerator.js';
import { scoreFinding } from './riskScorer.js';

const REMEDIATION_GUIDE = {
  'SQL Injection': 'Use parameterized queries / prepared statements. Never concatenate user input into SQL. Apply least-privilege DB accounts and WAF rules as defense-in-depth.',
  'Cross-Site Scripting (XSS)': 'Context-aware output encoding on all user-controlled reflections. Deploy Content-Security-Policy without unsafe-inline. Validate input on the server side.',
  'SSRF': 'Validate and allowlist all user-supplied URLs. Block private IP ranges (169.254.0.0/16, 10.0.0.0/8, 127.0.0.1). Disable unnecessary URL-fetch features.',
  'IDOR': 'Enforce server-side authorization checks on every object access. Use unpredictable identifiers (UUIDs). Never trust client-supplied IDs.',
};

function remediationFor(type) {
  for (const [key, text] of Object.entries(REMEDIATION_GUIDE)) {
    if (type.toLowerCase().includes(key.toLowerCase().split(' ')[0])) return text;
  }
  return 'Follow secure-coding best practices for this vulnerability class and validate the fix with a retest.';
}

/**
 * Render one finding as a markdown report section.
 */
export function findingToMarkdown(finding = {}) {
  const risk = scoreFinding(finding);
  const poc = generatePoC(finding);
  const lines = [
    `## ${finding.type || 'Finding'} — ${risk.severity} (${risk.score}/10)`,
    '',
    `**Target:** ${finding.url || 'n/a'}`,
    `**CWE:** ${finding.cwe || 'n/a'}`,
    `**Confidence:** ${finding.confidence || 'n/a'}`,
    '',
    '### Description',
    finding.description || `${finding.type} was identified at the target URL. See evidence and reproduction below.`,
    '',
    '### Evidence',
    '```',
    String(finding.evidence || 'n/a').slice(0, 500),
    '```',
    '',
    '### Reproduction Steps',
    ...poc.steps.map((s) => `- ${s}`),
    '',
    '### Proof of Concept (curl)',
    '```bash',
    poc.curl,
    '```',
    '',
    '### Impact',
    finding.impact || 'An attacker could exploit this to compromise confidentiality, integrity, or availability depending on the affected functionality.',
    '',
    '### Remediation',
    remediationFor(finding.type || ''),
    '',
    '---',
  ];
  return lines.join('\n');
}

/**
 * Render a full hunt report in markdown.
 */
export function huntReportToMarkdown({ target, startedAt, findings = [], techStack = [] }) {
  const scored = findings.map((f) => ({ ...f, risk: scoreFinding(f) }));
  const bySeverity = {};
  for (const f of scored) {
    const s = f.risk.severity;
    bySeverity[s] = (bySeverity[s] || 0) + 1;
  }
  const summary = Object.entries(bySeverity)
    .map(([s, n]) => `${n} ${s}`)
    .join(', ') || 'No findings';

  const lines = [
    `# Bug Bounty Report — ${target}`,
    '',
    `**Date:** ${new Date().toISOString().slice(0, 10)}`,
    `**Hunt started:** ${startedAt || 'n/a'}`,
    `**Technology detected:** ${techStack.join(', ') || 'n/a'}`,
    `**Summary:** ${summary}`,
    '',
    '---',
    '',
    ...scored
      .sort((a, b) => b.risk.score - a.risk.score)
      .map(findingToMarkdown),
    '',
    '*Generated by Dark-Matter autonomous bug bounty agent.*',
  ];
  return lines.join('\n');
}

export const AI_REPORT_WRITER = { findingToMarkdown, huntReportToMarkdown };
export default AI_REPORT_WRITER;
