/**
 * dmarcForensics.js — DMARC aggregate-report forensics for brand-impersonation detection.
 *
 * Part of the authorized bug-bounty reconnaissance toolkit: given DMARC
 * aggregate reports (RFC 7489 XML) for the target's domains, this module
 * surfaces unauthorized senders — IP addresses that failed SPF/DKIM alignment
 * while sending mail that claims to come from the brand's subdomains.
 *
 * Defensive framing only: findings feed phishing-takedown and mail-hygiene
 * recommendations. No outbound mail is generated by this module.
 */

/**
 * Parse a single DMARC aggregate-report XML document into structured rows.
 * Handles the <record><row> structure of RFC 7489 reports.
 *
 * @param {string} xml Raw DMARC aggregate XML (or a JSON string produced by a converter)
 * @returns {{domain: string|null, orgName: string|null, rows: object[]}}
 */
export function parseDmarcReport(xml) {
  if (!xml || typeof xml !== 'string') return { domain: null, orgName: null, rows: [] };
  const text = xml.trim();
  if (text.startsWith('{')) {
    return parseDmarcJson(text);
  }
  const tag = (name, scope) => {
    const m = scope.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`, 'i'));
    return m ? m[1].trim() : null;
  };
  const domain = tag('domain', tag('policy_published', text) || '');
  const orgName = tag('org_name', tag('report_metadata', text) || '');
  const rows = [];
  const recordRe = /<record>([\s\S]*?)<\/record>/gi;
  let rm;
  while ((rm = recordRe.exec(text)) !== null) {
    const rec = rm[1];
    const row = tag('row', rec) || '';
    const policy = tag('policy_evaluated', rec) || '';
    const auth = tag('auth_results', rec) || '';
    const spfBlock = tag('spf', auth) || '';
    const dkimBlock = tag('dkim', auth) || '';
    const identifiers = tag('identifiers', rec) || '';
    rows.push({
      sourceIp: tag('source_ip', row),
      count: parseInt(tag('count', row) || '0', 10) || 0,
      disposition: tag('disposition', policy),
      spfResult: tag('result', spfBlock),
      spfDomain: tag('domain', spfBlock),
      dkimResult: tag('result', dkimBlock),
      dkimDomain: tag('domain', dkimBlock),
      headerFrom: tag('header_from', identifiers),
      envelopeFrom: tag('envelope_from', identifiers),
    });
  }
  return { domain, orgName, rows };
}

/**
 * Parse the JSON form of a DMARC aggregate report (e.g. from a converter).
 * @param {string} jsonText
 */
export function parseDmarcJson(jsonText) {
  try {
    const doc = JSON.parse(jsonText);
    const rep = doc.feedback || doc;
    const rows = (rep.records || []).map(r => ({
      sourceIp: r?.row?.source_ip ?? null,
      count: Number(r?.row?.count ?? 0),
      disposition: r?.row?.policy_evaluated?.disposition ?? null,
      spfResult: r?.row?.policy_evaluated?.spf ?? r?.auth_results?.spf?.[0]?.result ?? null,
      spfDomain: r?.auth_results?.spf?.[0]?.domain ?? null,
      dkimResult: r?.auth_results?.dkim?.[0]?.result ?? null,
      dkimDomain: r?.auth_results?.dkim?.[0]?.domain ?? null,
      headerFrom: r?.identifiers?.header_from ?? null,
      envelopeFrom: r?.identifiers?.envelope_from ?? null,
    }));
    return {
      domain: rep?.policy_published?.domain ?? null,
      orgName: rep?.report_metadata?.org_name ?? null,
      rows,
    };
  } catch {
    return { domain: null, orgName: null, rows: [] };
  }
}

const FAIL_RESULTS = new Set(['fail', 'softfail', 'temperror', 'permerror', 'none']);

function isAuthFailure(row) {
  const spfBad = FAIL_RESULTS.has(String(row.spfResult || '').toLowerCase());
  const dkimBad = FAIL_RESULTS.has(String(row.dkimResult || '').toLowerCase());
  return spfBad && dkimBad;
}

/**
 * Find unauthorized senders: sources that failed both SPF and DKIM alignment
 * and are not on the known-authorized sender list.
 *
 * @param {{rows: object[]}} report Parsed report from parseDmarcReport
 * @param {{authorizedIps?: string[], authorizedDomains?: string[], brandDomains?: string[]}} options
 * @returns {object[]} findings sorted by volume, each with evidence
 */
export function findUnauthorizedSenders(report, options = {}) {
  if (!report || !Array.isArray(report.rows)) return [];
  const authorizedIps = new Set((options.authorizedIps || []).map(String));
  const authorizedDomains = new Set(
    (options.authorizedDomains || []).map(d => String(d).toLowerCase())
  );
  const brandDomains = (options.brandDomains || []).map(d => String(d).toLowerCase());
  const byIp = new Map();

  for (const row of report.rows) {
    if (!isAuthFailure(row)) continue;
    const ip = String(row.sourceIp || '');
    if (!ip || authorizedIps.has(ip)) continue;
    if (row.spfDomain && authorizedDomains.has(row.spfDomain.toLowerCase())) continue;
    if (row.dkimDomain && authorizedDomains.has(row.dkimDomain.toLowerCase())) continue;
    const entry = byIp.get(ip) || {
      sourceIp: ip,
      totalMessages: 0,
      claimedHeaderFrom: new Set(),
      evidence: [],
    };
    entry.totalMessages += row.count || 0;
    if (row.headerFrom) entry.claimedHeaderFrom.add(row.headerFrom);
    entry.evidence.push({
      count: row.count,
      disposition: row.disposition,
      spf: `${row.spfResult || 'unknown'} (${row.spfDomain || 'n/a'})`,
      dkim: `${row.dkimResult || 'unknown'} (${row.dkimDomain || 'n/a'})`,
      headerFrom: row.headerFrom,
    });
    byIp.set(ip, entry);
  }

  return [...byIp.values()]
    .map(e => {
      const claimsBrand = [...e.claimedHeaderFrom].some(h =>
        brandDomains.some(b => h.toLowerCase() === b || h.toLowerCase().endsWith(`.${b}`))
      );
      return {
        type: 'unauthorized-sender',
        sourceIp: e.sourceIp,
        totalMessages: e.totalMessages,
        claimedHeaderFrom: [...e.claimedHeaderFrom],
        impersonatesBrandDomain: claimsBrand,
        severity: claimsBrand ? 'high' : 'medium',
        evidence: e.evidence,
      };
    })
    .sort((a, b) => b.totalMessages - a.totalMessages);
}

/**
 * Summarize a parsed report: top offending IPs, pass/fail totals, domains seen.
 * @param {{rows: object[]}} report
 */
export function summarizeDmarcThreat(report) {
  if (!report || !Array.isArray(report.rows)) {
    return { totalMessages: 0, failedMessages: 0, failedIps: 0, topOffenders: [] };
  }
  let totalMessages = 0;
  let failedMessages = 0;
  const perIp = new Map();
  for (const row of report.rows) {
    const n = row.count || 0;
    totalMessages += n;
    if (isAuthFailure(row)) {
      failedMessages += n;
      perIp.set(row.sourceIp, (perIp.get(row.sourceIp) || 0) + n);
    }
  }
  const topOffenders = [...perIp.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([ip, count]) => ({ sourceIp: ip, failedMessages: count }));
  return { totalMessages, failedMessages, failedIps: perIp.size, topOffenders };
}

export const DMARC_FORENSICS = {
  parseDmarcReport,
  parseDmarcJson,
  findUnauthorizedSenders,
  summarizeDmarcThreat,
};

export default DMARC_FORENSICS;
