/**
 * frameworkIntel.js — JavaScript framework fingerprinting and build-mode detection.
 *
 * Identifies which frontend framework shipped a bundle and whether it was
 * built for development or production, from passive bundle signatures the
 * framework itself embeds (version strings, devtools hooks, dev warnings).
 * This is defensive asset intelligence for an authorized hunt: framework and
 * build mode determine which known misconfigurations are worth checking.
 *
 * Ideas covered:
 *  00683 JS framework fingerprinting — identify React/Vue/Angular/Svelte
 *          versions from bundle signatures and global hooks.
 *  00684 Framework build-mode detection — detect development vs production
 *          builds from warning strings and devtools hooks.
 */

/**
 * Fingerprint signatures. Each entry lists evidence regexes; the first
 * version-capture group that matches wins for the version field.
 */
const SIGNATURES = [
  {
    framework: 'react',
    hooks: [/__REACT_DEVTOOLS_GLOBAL_HOOK__/, /ReactCurrentOwner/, /createElement/],
    versions: [
      /react-dom@(\d+\.\d+\.\d+)/,
      /"react-dom"\s*:\s*"(\d+\.\d+\.\d+)"/,
      /React\s+v?(\d+\.\d+\.\d+)/,
      /react\.production\.min\.js/,
    ],
    versioned: m => (m[1] ? m[1] : null),
  },
  {
    framework: 'vue',
    hooks: [/__VUE_DEVTOOLS_GLOBAL_HOOK__/, /__VUE_OPTIONS_API__/, /__VUE_PROD_DEVTOOLS__/],
    versions: [
      /vue@(\d+\.\d+\.\d+)/,
      /"version"\s*:\s*"(\d+\.\d+\.\d+)"[\s\S]{0,120}?vue/i,
      /Vue\.version\s*=\s*["'](\d+\.\d+\.\d+)["']/,
      /version\s*:\s*["'](\d+\.\d+\.\d+)["'][\s\S]{0,80}__VUE/,
    ],
  },
  {
    framework: 'angular',
    hooks: [/__ngContext__/, /ng-version/, /platform-browser/, /@angular\/core/],
    versions: [
      /ng-version="(\d+\.\d+\.\d+)"/,
      /ng-version\s*:\s*["'](\d+\.\d+\.\d+)["']/,
      /@angular\/core@(\d+\.\d+\.\d+)/,
      /VERSION\s*=\s*\{[^}]*full\s*:\s*["'](\d+\.\d+\.\d+)["']/,
    ],
  },
  {
    framework: 'svelte',
    hooks: [/__svelte/, /SvelteComponent/, /svelte\/internal/],
    versions: [
      /generated by Svelte v(\d+\.\d+\.\d+)/,
      /svelte@(\d+\.\d+\.\d+)/,
      /Svelte v(\d+\.\d+\.\d+)/,
    ],
  },
  {
    framework: 'next.js',
    hooks: [/__NEXT_DATA__/, /next\/dist\//, /__next_f/, /_next\/static/],
    versions: [/next@(\d+\.\d+\.\d+)/, /"next"\s*:\s*"(\d+\.\d+\.\d+)"/],
  },
  {
    framework: 'nuxt',
    hooks: [/__NUXT__/, /\$nuxt/, /nuxt-link/],
    versions: [/nuxt@(\d+\.\d+\.\d+)/, /"nuxt"\s*:\s*"(\d+\.\d+\.\d+)"/],
  },
];

/**
 * Fingerprint frameworks present in a bundle (idea 00683).
 *
 * @param {string} bundle Bundle text observed on the authorized target.
 * @returns {Array<{framework: string, version: string|null, confidence: 'high'|'medium'|'low', evidence: string[]}>}
 */
export function fingerprintFrameworks(bundle) {
  const text = String(bundle || '');
  const found = [];
  for (const sig of SIGNATURES) {
    const evidence = [];
    for (const re of sig.hooks) {
      const m = text.match(re);
      if (m) evidence.push(m[0].slice(0, 48));
      if (evidence.length >= 3) break;
    }
    if (evidence.length === 0) continue;
    let version = null;
    for (const vre of sig.versions) {
      const m = text.match(vre);
      if (m && m[1]) {
        version = m[1];
        evidence.push('version:' + version);
        break;
      }
    }
    const confidence = version ? 'high' : evidence.length >= 2 ? 'medium' : 'low';
    found.push({ framework: sig.framework, version, confidence, evidence });
  }
  return found;
}

const DEV_SIGNALS = [
  { name: 'react-dev-warning', re: /Warning:\s+[A-Z][\s\S]{0,60}React/i, weight: 3 },
  { name: 'vue-dev-warn', re: /\[Vue warn\]/, weight: 3 },
  { name: 'angular-isdevmode', re: /isDevMode\s*\(\s*\)/, weight: 2 },
  { name: 'node-env-dev-check', re: /NODE_ENV\s*!==?\s*["']production["']/, weight: 2 },
  {
    name: 'devtools-hook-enabled',
    re: /__REACT_DEVTOOLS_GLOBAL_HOOK__\.isDisabled\s*=\s*!1/,
    weight: 2,
  },
  { name: 'console-warn-heavy', re: /console\.warn\(/, weight: 1 },
  { name: 'development-string', re: /\bdevelopment\b/i, weight: 1 },
  { name: 'svelte-dev-block', re: /\/\*\s*dev\s*\*\//i, weight: 2 },
  { name: 'hmr-runtime', re: /webpackHotUpdate|hot-module-replacement|vite\/client/, weight: 3 },
];

const PROD_SIGNALS = [
  { name: 'production-min-suffix', re: /\.production\.min\.js/, weight: 3 },
  { name: 'node-env-prod', re: /NODE_ENV\s*[:=]\s*["']production["']/, weight: 2 },
  { name: 'prod-devtools-flag', re: /__VUE_PROD_DEVTOOLS__/, weight: 1 },
  { name: 'warning-stripped', re: /production build/i, weight: 1 },
];

/**
 * Detect whether a bundle is a development or production build (idea 00684).
 *
 * @param {string} bundle Bundle text.
 * @returns {{mode: 'development'|'production'|'unknown', confidence: 'high'|'medium'|'low', devScore: number, prodScore: number, devHits: string[], prodHits: string[]}}
 */
export function detectBuildMode(bundle) {
  const text = String(bundle || '');
  const devHits = [];
  const prodHits = [];
  let devScore = 0;
  let prodScore = 0;
  for (const s of DEV_SIGNALS) {
    if (s.re.test(text)) {
      devHits.push(s.name);
      devScore += s.weight;
    }
  }
  for (const s of PROD_SIGNALS) {
    if (s.re.test(text)) {
      prodHits.push(s.name);
      prodScore += s.weight;
    }
  }
  let mode = 'unknown';
  if (devScore > prodScore) mode = 'development';
  else if (prodScore > devScore) mode = 'production';
  const spread = Math.abs(devScore - prodScore);
  const confidence = spread >= 4 ? 'high' : spread >= 2 ? 'medium' : 'low';
  return { mode, confidence, devScore, prodScore, devHits, prodHits };
}

export const FRAMEWORK_INTEL = {
  ideas: ['00683', '00684'],
  description: 'JS framework fingerprinting and dev/prod build-mode detection.',
};

export default FRAMEWORK_INTEL;
