/**
 * punycodeVariantEnumerator.js — IDN punycode (xn--) variant enumeration engine.
 *
 * Covers idea-bank item 0302:
 *  - 0302 Punycode variant enumeration — enumerate xn-- punycode domains
 *    resembling the brand to find IDN-based phishing infrastructure.
 *
 * Pure functions only: the engine builds the punycode (xn--) forms of
 * brand-like IDN labels using a userland punycode implementation; callers
 * perform DNS/registration lookups themselves. No live lookups here.
 */

/**
 * Minimal RFC 3492 punycode encoder (label-only), so this engine has no
 * external dependency. Behaviour matches the WHATWG URL punycode path used
 * by browsers: any label containing non-ASCII code points is encoded as
 * `xn--<punycode>`.
 * @param {string} input Unicode label
 * @returns {string} ASCII-safe label (xn-- prefixed when non-ASCII)
 */
function punycodeEncodeLabel(input) {
  const output = [];
  const base = 36;
  const tMin = 1;
  const tMax = 26;
  const skew = 38;
  const damp = 700;
  const initialBias = 72;
  const initialN = 128;
  const delimiter = '-';

  const codePoints = [...input].map((ch) => ch.codePointAt(0));
  const isAscii = (cp) => cp < 0x80;

  for (const cp of codePoints) {
    if (isAscii(cp)) output.push(String.fromCodePoint(cp));
  }
  const basicLength = output.length;
  if (basicLength) output.push(delimiter);

  let n = initialN;
  let delta = 0;
  let bias = initialBias;
  let handled = basicLength;

  const adapt = (d, numPoints, firstTime) => {
    d = firstTime ? Math.floor(d / damp) : d >> 1;
    d += Math.floor(d / numPoints);
    let k = 0;
    while (d > ((base - tMin) * tMax) >> 1) {
      d = Math.floor(d / (base - tMin));
      k += base;
    }
    return k + Math.floor(((base - tMin + 1) * d) / (d + skew));
  };

  const digitToChar = (d) => String.fromCharCode(d + 22 + 75 * (d < 26 ? 1 : 0));

  while (handled < codePoints.length) {
    let m = Number.MAX_SAFE_INTEGER;
    for (const cp of codePoints) {
      if (cp >= n && cp < m) m = cp;
    }
    delta += (m - n) * (handled + 1);
    n = m;
    for (const cp of codePoints) {
      if (cp < n) delta++;
      if (cp === n) {
        let q = delta;
        for (let k = base; ; k += base) {
          const t = k <= bias ? tMin : k >= bias + tMax ? tMax : k - bias;
          if (q < t) break;
          output.push(digitToChar(t + ((q - t) % (base - t))));
          q = Math.floor((q - t) / (base - t));
        }
        output.push(digitToChar(q));
        bias = adapt(delta, handled + 1, handled === basicLength);
        delta = 0;
        handled++;
      }
    }
    delta++;
    n++;
  }

  const hasNonAscii = codePoints.some((cp) => !isAscii(cp));
  return (hasNonAscii ? 'xn--' : '') + output.join('');
}

/**
 * Split a domain into label parts, lowercase, trailing-dot stripped.
 * @param {string} domain
 * @returns {string[]}
 */
export function splitDomainLabels(domain) {
  if (!domain) return [];
  return String(domain)
    .trim()
    .toLowerCase()
    .replace(/\.$/, '')
    .split('/')
    .shift()
    .split('.')
    .filter(Boolean);
}

/**
 * Encode a Unicode domain label to its punycode ASCII form.
 * @param {string} label
 * @returns {{ascii: string, isPunycode: boolean}}
 */
export function encodePunycodeLabel(label) {
  const clean = String(label || '').toLowerCase().replace(/^-+|-+$/g, '');
  const ascii = punycodeEncodeLabel(clean);
  return { ascii, isPunycode: ascii.startsWith('xn--') };
}

/**
 * Enumerate the punycode (xn--) forms of brand-like IDN labels. Each input
 * label is a Unicode string that "looks like" the brand (e.g. generated by
 * the homoglyph engine or supplied from an IDN wordlist); this engine maps
 * it to the DNS-visible ASCII form attackers would actually register.
 *
 * @param {string[]} unicodeLabels Unicode labels resembling the brand
 * @param {string[]} tlds TLDs to append (without leading dot)
 * @returns {{unicode: string, ascii: string, tld: string, domain: string}[]}
 */
export function enumeratePunycodeVariants(unicodeLabels = [], tlds = ['com', 'net', 'org']) {
  const results = [];
  const seen = new Set();
  for (const raw of unicodeLabels || []) {
    const label = String(raw || '').trim().toLowerCase();
    if (!label) continue;
    const { ascii } = encodePunycodeLabel(label);
    for (const tld of tlds || []) {
      const clean = String(tld).replace(/^\./, '').toLowerCase();
      if (!clean) continue;
      const domain = `${ascii}.${clean}`;
      if (seen.has(domain)) continue;
      seen.add(domain);
      results.push({ unicode: label, ascii, tld: clean, domain });
    }
  }
  return results.sort((a, b) => a.domain.localeCompare(b.domain));
}

/**
 * Check whether a domain is an IDN (punycode) variant that decodes to a
 * brand-like label. Uses a forgiving similarity test: exact match after
 * normalizing separators and digits-as-letters is "high"; one-character
 * difference is "medium".
 *
 * @param {string} domain Candidate xn-- domain
 * @param {string} brand Brand token
 * @returns {{isPunycode: boolean, decoded: string, similarity: 'high'|'medium'|'low'|'none', looksLikeBrand: boolean}}
 */
export function detectPunycodeBrandVariant(domain, brand) {
  const result = { isPunycode: false, decoded: '', similarity: 'none', looksLikeBrand: false };
  const labels = splitDomainLabels(domain);
  const xn = labels.find((l) => l.startsWith('xn--'));
  if (!xn) return result;
  result.isPunycode = true;

  // Decode back to Unicode via a local lookup-free path: re-encode against
  // candidates is impractical, so decode with a small pure decoder.
  const decoded = decodePunycodeLabel(xn);
  result.decoded = decoded;

  const norm = (s) => String(s || '').toLowerCase().replace(/[\s_\-\.]+/g, '');
  const brandNorm = norm(brand);
  const decodedNorm = norm(decoded);
  if (!brandNorm) return result;

  if (decodedNorm === brandNorm) {
    result.similarity = 'high';
  } else if (editDistance(decodedNorm, brandNorm) === 1) {
    result.similarity = 'medium';
  } else if (
    decodedNorm.includes(brandNorm) ||
    (decodedNorm.length >= 4 && brandNorm.includes(decodedNorm))
  ) {
    result.similarity = 'low';
  }
  result.looksLikeBrand = result.similarity !== 'none';
  return result;
}

/**
 * Pure punycode decoder for a single xn-- label (RFC 3492).
 * @param {string} label ASCII label starting with xn--
 * @returns {string} Decoded Unicode label
 */
function decodePunycodeLabel(label) {
  const base = 36;
  const tMin = 1;
  const tMax = 26;
  const skew = 38;
  const damp = 700;
  const initialBias = 72;
  const initialN = 128;
  const delimiter = '-';

  const body = label.slice(4);
  const d = body.lastIndexOf(delimiter);
  const output = [];
  if (d >= 0) {
    for (const ch of body.slice(0, d)) output.push(ch.codePointAt(0));
  }
  const rest = d >= 0 ? body.slice(d + 1) : body;
  const digitToInt = (c) => {
    const cp = c.charCodeAt(0);
    if (cp >= 48 && cp <= 57) return cp - 48 + 26;
    if (cp >= 65 && cp <= 90) return cp - 65;
    if (cp >= 97 && cp <= 122) return cp - 97;
    return -1;
  };

  let n = initialN;
  let i = 0;
  let bias = initialBias;
  let pos = 0;

  while (pos < rest.length) {
    const oldi = i;
    let w = 1;
    for (let k = base; ; k += base) {
      if (pos >= rest.length) return body; // malformed: return raw
      const digit = digitToInt(rest[pos++]);
      if (digit < 0) return body;
      i += digit * w;
      const t = k <= bias ? tMin : k >= bias + tMax ? tMax : k - bias;
      if (digit < t) break;
      w *= base - t;
    }
    const out = output.length + 1;
    bias = adaptBias(i - oldi, out, oldi === 0);
    n += Math.floor(i / out);
    i %= out;
    output.splice(i, 0, n);
    i++;
  }

  return output.map((cp) => String.fromCodePoint(cp)).join('');

  function adaptBias(delta, numPoints, firstTime) {
    delta = firstTime ? Math.floor(delta / damp) : delta >> 1;
    delta += Math.floor(delta / numPoints);
    let k = 0;
    while (delta > ((base - tMin) * tMax) >> 1) {
      delta = Math.floor(delta / (base - tMin));
      k += base;
    }
    return k + Math.floor(((base - tMin + 1) * delta) / (delta + skew));
  }
}

/**
 * Levenshtein edit distance between two short strings.
 * @param {string} a
 * @param {string} b
 * @returns {number}
 */
export function editDistance(a, b) {
  const x = String(a || '');
  const y = String(b || '');
  if (x === y) return 0;
  if (!x.length) return y.length;
  if (!y.length) return x.length;
  const prev = new Array(y.length + 1);
  const cur = new Array(y.length + 1);
  for (let j = 0; j <= y.length; j++) prev[j] = j;
  for (let i = 1; i <= x.length; i++) {
    cur[0] = i;
    for (let j = 1; j <= y.length; j++) {
      const cost = x[i - 1] === y[j - 1] ? 0 : 1;
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost);
    }
    for (let j = 0; j <= y.length; j++) prev[j] = cur[j];
  }
  return prev[y.length];
}

/**
 * Triage candidate xn-- domains: separate brand-like IDN squats from
 * unrelated punycode domains.
 *
 * @param {string[]} domains Candidate domains (may mix xn-- and ASCII)
 * @param {string} brand Brand token
 * @returns {{brandLike: {domain: string, decoded: string, similarity: string}[], unrelated: string[]}}
 */
export function triagePunycodeDomains(domains = [], brand) {
  const brandLike = [];
  const unrelated = [];
  for (const d of domains || []) {
    const det = detectPunycodeBrandVariant(d, brand);
    if (!det.isPunycode) {
      unrelated.push(String(d));
      continue;
    }
    if (det.looksLikeBrand) {
      brandLike.push({ domain: String(d), decoded: det.decoded, similarity: det.similarity });
    } else {
      unrelated.push(String(d));
    }
  }
  const rank = { high: 0, medium: 1, low: 2 };
  return {
    brandLike: brandLike.sort((a, b) => (rank[a.similarity] ?? 3) - (rank[b.similarity] ?? 3)),
    unrelated,
  };
}
