/**
 * wafHeaderFingerprinter.js — WAF fingerprinting via header analysis.
 *
 * Idea 00388: identify WAF vendors by response headers, cookie names, and
 * block-page markers.
 *
 * Takes captured HTTP response metadata (status, headers, Set-Cookie names,
 * and an optional block-page body snippet) and matches it against a vendor
 * signature table. Pure, offline, and strictly defensive: it only names the
 * protecting vendor so the agent can adapt reporting, never to evade.
 */

const WAF_SIGNATURES = [
  {
    vendor: 'Cloudflare',
    weight: 3,
    headers: [/^cf-ray$/i, /^cf-cache-status$/i, /^__cf_bm$/i],
    cookies: [/^__cf_bm$/i, /^cf_clearance$/i, /^_cfuvid$/i],
    server: /cloudflare/i,
    body: /cloudflare ray id|attention required! \| cloudflare|cf-chl-/i,
  },
  {
    vendor: 'AWS WAF / CloudFront',
    weight: 3,
    headers: [/^x-amz-cf-id$/i, /^x-amz-cf-pop$/i, /^x-amzn-requestid$/i],
    cookies: [/^aws-waf-token$/i],
    server: /cloudfront/i,
    body: /generated by cloudfront|request blocked/i,
  },
  {
    vendor: 'Akamai',
    weight: 3,
    headers: [/^x-akamai-transformed$/i, /^akamai-origin-hop$/i],
    cookies: [/^ak_bmsc$/i, /^bm_sz$/i, /^_abck$/i],
    server: /akamai/i,
    body: /akamai edge|reference #[0-9a-f.]+/i,
  },
  {
    vendor: 'Imperva / Incapsula',
    weight: 3,
    headers: [/^x-cdn$/i],
    cookies: [/^incap_ses_/i, /^visid_incap_/i, /^___utmvc$/i],
    server: /incapsula/i,
    body: /incapsula incident id|_incap_/i,
  },
  {
    vendor: 'F5 BIG-IP ASM',
    weight: 2,
    headers: [/^x-waf-event$/i],
    cookies: [/^f5avr/i, /^bigipserver/i, /^ts[0-9a-f]{6}$/i],
    server: /big-ip|bigip/i,
    body: /the requested url was rejected|f5 networks/i,
  },
  {
    vendor: 'Sucuri',
    weight: 2,
    headers: [/^x-sucuri-id$/i, /^x-sucuri-cache$/i],
    cookies: [],
    server: /sucuri/i,
    body: /sucuri website firewall|cloudproxy/i,
  },
  {
    vendor: 'Fastly',
    weight: 2,
    headers: [/^x-served-by$/i, /^x-cache-hits$/i, /^fastly-restarts$/i],
    cookies: [],
    server: /fastly/i,
    body: null,
  },
  {
    vendor: 'Wordfence',
    weight: 2,
    headers: [],
    cookies: [/^wfvt_/i, /^wordfence_verifiedhuman$/i],
    server: null,
    body: /wordfence|your access to this site has been limited/i,
  },
  {
    vendor: 'Cloud Armor (GCP)',
    weight: 2,
    headers: [/^x-cloud-trace-context$/i],
    cookies: [],
    server: /gws/i,
    body: /error 403.*forbidden/i,
  },
  {
    vendor: 'Azure Front Door / WAF',
    weight: 2,
    headers: [/^x-azure-ref$/i, /^x-fd-int-routes$/i],
    cookies: [/^asctx/i],
    server: /azure/i,
    body: /our services aren't available right now/i,
  },
  {
    vendor: 'ModSecurity',
    weight: 1,
    headers: [],
    cookies: [],
    server: /mod_security|modsecurity/i,
    body: /mod_security|not acceptable!|error 406/i,
  },
];

/**
 * @typedef {Object} ResponseMeta
 * @property {number} status
 * @property {Record<string,string|string[]>} headers
 * @property {string[]} [cookies] - Cookie names from Set-Cookie.
 * @property {string} [bodySnippet] - First ~4KB of a block/error page.
 * @property {string} [url]
 */

/**
 * Fingerprint the WAF (if any) protecting a target from response metadata.
 * @param {ResponseMeta} response
 * @returns {{vendor: string|null, confidence: 'high'|'medium'|'low'|'none', matches: object[], scores: object[]}}
 */
export function fingerprintWaf(response = {}) {
  const headers = response.headers || {};
  const headerNames = Object.keys(headers);
  const cookieNames = response.cookies || [];
  const server = [].concat(headers['server'] || headers['Server'] || []).join(' ');
  const body = response.bodySnippet || '';

  const scores = [];
  for (const sig of WAF_SIGNATURES) {
    let score = 0;
    const evidence = [];
    for (const re of sig.headers || []) {
      if (headerNames.some((n) => re.test(n))) { score += sig.weight; evidence.push(`header matches ${re}`); }
    }
    for (const re of sig.cookies || []) {
      if (cookieNames.some((n) => re.test(n))) { score += sig.weight; evidence.push(`cookie matches ${re}`); }
    }
    if (sig.server && sig.server.test(server)) { score += sig.weight; evidence.push(`Server header: ${server.slice(0, 80)}`); }
    if (sig.body && sig.body.test(body)) { score += sig.weight; evidence.push('block-page body marker'); }
    if (score > 0) scores.push({ vendor: sig.vendor, score, evidence });
  }
  scores.sort((a, b) => b.score - a.score);

  const top = scores[0];
  const second = scores[1];
  let vendor = null;
  let confidence = 'none';
  if (top) {
    vendor = top.vendor;
    if (top.score >= 6 && (!second || top.score - second.score >= 3)) confidence = 'high';
    else if (top.score >= 3) confidence = 'medium';
    else confidence = 'low';
  }
  return {
    vendor,
    confidence,
    matches: top ? top.evidence : [],
    scores: scores.slice(0, 5),
  };
}

/**
 * Analyze a batch of responses (e.g. baseline + error pages) for consensus.
 * @param {ResponseMeta[]} responses
 */
export function fingerprintWafBatch(responses = []) {
  const per = responses.map((r) => fingerprintWaf(r));
  const votes = new Map();
  for (const p of per) {
    if (!p.vendor) continue;
    votes.set(p.vendor, (votes.get(p.vendor) || 0) + 1);
  }
  const ranked = [...votes.entries()].sort((a, b) => b[1] - a[1]);
  const consensus = ranked.length ? ranked[0][0] : null;
  const unanimous = ranked.length === 1 && per.every((p) => p.vendor === consensus);
  return {
    consensus,
    confidence: !consensus ? 'none' : unanimous ? 'high' : ranked[0][1] > (ranked[1]?.[1] || 0) ? 'medium' : 'low',
    votes: ranked.map(([vendor, count]) => ({ vendor, count })),
    perResponse: per,
  };
}

/**
 * Build a report finding.
 * @param {ReturnType<typeof fingerprintWafBatch>} result
 * @param {string} targetLabel
 */
export function wafFinding(result, targetLabel = 'target') {
  return {
    title: result.consensus
      ? `WAF fingerprinted — ${result.consensus} protecting ${targetLabel}`
      : `No WAF identified for ${targetLabel}`,
    severity: 'Info',
    confidence: result.confidence,
    vendor: result.consensus,
    votes: result.votes,
    evidence: result.consensus
      ? `Header/cookie/block-page analysis converges on ${result.consensus} ` +
        `(${result.votes.map((v) => `${v.vendor}:${v.count}`).join(', ')}).`
      : 'No vendor signature matched the observed responses.',
  };
}

export const WAF_HEADER_FINGERPRINTER = { fingerprintWaf, fingerprintWafBatch, wafFinding, WAF_SIGNATURES };
export default WAF_HEADER_FINGERPRINTER;
