/**
 * vmRunnerClient.js — minimal HTTP client for the local VM Runner (design §2).
 *
 * The VM Runner is a separate Node service on the USER'S machine
 * (http://127.0.0.1:4100). It is the only path by which shell-type hunt
 * actions reach the Kali VM sandbox — tool binaries are never spawned on
 * the backend host when a VM session is attached.
 *
 * This client carries NO credentials storage: the per-session bearer token
 * (generated by POST /vm/start, held in frontend memory) is passed in by the
 * caller. Only the values named by the caller are sent, to the runner only.
 */

const DEFAULT_BASE_URL = 'http://127.0.0.1:4100';

/**
 * Execute a shell command inside the VM session's guest.
 *
 * @param {object} opts
 * @param {string} [opts.baseUrl] — VM Runner base URL (default 127.0.0.1:4100)
 * @param {string|null} [opts.token] — per-session bearer token (optional; sent only when provided)
 * @param {string} opts.sessionId
 * @param {string} opts.command
 * @param {string} [opts.cwd]
 * @param {number} [opts.timeoutMs=120000]
 * @returns {Promise<{ exit_code: number, stdout: string, stderr: string, timed_out: boolean }>}
 */
export async function execOnVm({ baseUrl = DEFAULT_BASE_URL, token = null, sessionId, command, cwd, timeoutMs = 120_000 } = {}) {
  if (!sessionId) throw new Error('execOnVm: sessionId is required');
  if (!command) throw new Error('execOnVm: command is required');
  const base = String(baseUrl || DEFAULT_BASE_URL).replace(/\/+$/, '');
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs + 15_000);
  try {
    const res = await fetch(`${base}/vm/exec`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      },
      signal: controller.signal,
      body: JSON.stringify({ sessionId, command, cwd, timeoutMs }),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`VM runner HTTP ${res.status}: ${text.slice(0, 200)}`);
    }
    const data = await res.json();
    if (data && data.ok === false) {
      throw new Error(`VM runner error [${data.code || 'unknown'}]: ${data.message || 'request failed'}`);
    }
    return {
      exit_code: Number.isFinite(Number(data?.exit_code)) ? Number(data.exit_code) : -1,
      stdout: String(data?.stdout ?? ''),
      stderr: String(data?.stderr ?? ''),
      timed_out: Boolean(data?.timed_out),
    };
  } catch (err) {
    if (err?.name === 'AbortError') throw new Error(`VM runner exec timed out after ${timeoutMs}ms`);
    throw err;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Probe whether the VM Runner is reachable (used for friendly error paths).
 * Resolves true/false — never throws.
 */
export async function isVmRunnerUp({ baseUrl = DEFAULT_BASE_URL, timeoutMs = 5000 } = {}) {
  const base = String(baseUrl || DEFAULT_BASE_URL).replace(/\/+$/, '');
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`${base}/health`, { signal: controller.signal });
    return res.ok;
  } catch {
    return false;
  } finally {
    clearTimeout(timer);
  }
}

export default { execOnVm, isVmRunnerUp };
